### ISSUE TITLE
I get `set: Illegal option -o pipefail`

### ISSUE THREAD

**Issue by pranaypratyush** [tsertkov/wp-headless#32]
```
ubuntu@instance-20200302-1127:~/wpheadless$ sudo ./run-task install
./run-task: 3: set: Illegal option -o pipefail
```

I modified the shebang to `#!/usr/bin/env bash` and it didn't throw that error.

**Comment by tsertkov** [comment]
Actually `pipefail` can be removed for `run-task` and `docker-compose` scripts for POSIX compatibility.
